### ISSUE TITLE
Infection rate data unavailable

### ISSUE THREAD

**Issue by MrSimonEmms** [britishredcrosssociety/local-lockdown#23]
I was checking the #19 update worked and I can't see any infection rate data wherever I look. Is that correct?

![image](https://user-images.githubusercontent.com/275848/93521631-416ea600-f928-11ea-973d-ddd321f165e5.png)

**Comment by izzy-everall** [comment]
mm was this even after you changed local authorities? Adur doesn't have infection rate stats but if you try liverpool for example that should appear.. quite a few don't have infection rate stats. 
one thing that does need to be changed is the title of the infection rate plot.. i think per 100,000 people tested should be just per 100,000.

**Comment by MikeJohnPage** [comment]
@MrSimonEmms thanks for checking the dashboard and flagging.

Yes, unfortunately infection rate stats aren't available for every LA, only a small subset. Admittedly perhaps there may be a better way of explaining this / changing the plot to reflect this. I will leave this issue open as a remind for a fix.

@izzy-everall I am going to be adding some more data/plots today so will update the title then.

**Comment by MrSimonEmms** [comment]
No problem.

@izzy-everall yes, when I go to Liverpool, I see data there. So there's no issue with the component which hs the main thing.

@MikeJohnPage maybe improving the wording would help this. Although not a UX expert, I'm a non-technical user in this case - maybe the "Data Unavailable" should just be expanded to something like "Data Unavailable for $LocalAuthority - please select a different local authority from the sidebar"
